name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 1.1.1
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
  very_good_analysis: ^7.0.0
