name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 0.7.0
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  very_good_analysis: ^5.0.0+1
