name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 1.0.0
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
